### ISSUE TITLE
IXI data preparation steps

### ISSUE THREAD

**Issue by op1009** [ci-ber/THOR_DDPM#2]
Congrats to authors for MICCAI24 accept!

After downloading the dataset, what are the steps needed to be followed for data preparation:
- do we need to extract each slices axially and save as png/jpg ?
- what is the train-val-test splitting strategy used ?

**Comment by ci-ber** [comment]
- The easiest/fastest setup would be extracting mid-axial slices, pre-processing (i.e., padding and re-scaling to 128x128), and saving them as png. It's possible to train on all axial slices, but generative models aim to learn a distribution and expect a drop in performance unless conditioned for instance on the slice number (The model does not know what anatomy to reconstruct from pure noise with no guidance). -- Check also this for 3D AD (https://arxiv.org/pdf/2403.14499). 

- The train-val-test for IXI was random, and we provided the CSV files containing exactly which images were used for reproducibility. Under projects->thor->configs->brain->thor.yaml you can see the configuration used to train the model which would point you to the data folders:        
          train:
            - './data/CAPS_IXI/splits/ixi-t1_atlas_train_2D.csv'
          val:
            - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
          test:
            - './data/CAPS_IXI/splits/ixi-t1_test_2D.csv')

**Comment by op1009** [comment]
Only these 2 csv files  are present in [data/CAPS_IXI/splits](data/CAPS_IXI/splits)
- ixi_atlas_normal_train.csv
- ixi_normal_train.csv

**Comment by ci-ber** [comment]
Thanks, I added the missing files. You should also be able to find the processed mid axial slices (IXI) in the png folder

**Comment by op1009** [comment]
> It's possible to train on all axial slices, but generative models aim to learn a distribution and expect a drop in performance unless conditioned for instance on the slice number (The model does not know what anatomy to reconstruct from pure noise with no guidance).


- The splits you have used in thor.yaml:
```yaml
data_dir:
          train:
            - './data/CAPS_IXI/splits/ixi-t1_atlas_train_2D.csv'
            # 465 from IXI + 218 from ATLAS 
          val:
            - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
            # 58 from IXI
          test:
            - './data/CAPS_IXI/splits/ixi-t1_test_2D.csv'
            # 58 from IXI
```
- IXI dataset contains MRI scans of 600 subject.
- Each MRI is of shape (256, 256, 146), so there will be 146 axial slice for a single subject. Have you used only 1 slice from 1 subject's MRI ?
